theme = "dark_plus"

[editor]
shell = ["zsh", "-c"]
line-number = "relative"
cursorline = true
idle-timeout = 0
completion-trigger-len = 1
completion-replace = true
rulers = [80]
default-line-ending = "lf"
popup-border = "all"

[editor.statusline]
mode = { normal = "NORMAL", insert = "INSERT", select = "SELECT" }

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[keys.normal]
"C-." = "code_action"

[keys.insert]
C-space = "completion"
