import = ["~/Library/Application Support/alacritty/tomorrow-night-variant.toml"]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
opacity = 0.8

[[hints.enabled]]
command = "open"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Command"
