# Tomorrow Night Variant (From Alacritty <= 0.12.3)

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"
dim_foreground = '#828482'
bright_foreground = '#eaeaea'

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search]
matches = { foreground = "#181818", background = "#9e6a03" }
focused_match = { foreground = "#181818", background = "#ecb463" }

[colors.hints.start]
foreground = '#1d1f21'
background = '#e9ff5e'

[colors.hints.end]
foreground = '#e9ff5e'
background = '#1d1f21'

[colors.selection]
text = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black = '#1d1f21'
red = '#cc6666'
green = '#b5bd68'
yellow = '#f0c674'
blue = '#81a2be'
magenta = '#b294bb'
cyan = '#8abeb7'
white = '#c5c8c6'

[colors.bright]
black = '#666666'
red = '#d54e53'
green = '#b9ca4a'
yellow = '#e7c547'
blue = '#7aa6da'
magenta = '#c397d8'
cyan = '#70c0b1'
white = '#eaeaea'

[colors.dim]
black = '#131415'
red = '#864343'
green = '#777c44'
yellow = '#9e824c'
blue = '#556a7d'
magenta = '#75617b'
cyan = '#5b7d78'
white = '#828482'
